drinc/drinc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("drinks/", include("ratings.urls")),
    path("admin/", admin.site.urls),
]

drinc/ratings/urls.py
from django.urls import path

from . import views

app_name = "ratings"
urlpatterns = [
    # ex: /polls/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /drink/5/
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # ex: /drink/5/ratings/
    path("<int:pk>/ratings/", views.RatingsView.as_view(), name="ratings"),
    # ex: /drink/5/vote/
    path("<int:drink_id>/vote/", views.vote, name="vote"),
]

drinc/ratings/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


class Category(models.Model):
    # TODO: valutare se corretto tenere mischiate categorie drink e ingredienti
    #       Magari per i drink valutare tags (Multipli)
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Drink(models.Model):
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.CharField(max_length=300)  # For string fields better to use empty strings instead of null ones
    ingredients = models.ManyToManyField(Ingredient)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        ordering = ["price"]

    def __str__(self):
        return f"{self.name} - {self.price}€"


class Menu(models.Model):
    name = models.CharField(max_length=150)
    dateL = models.DateField(verbose_name="Date Launch")
    dateC = models.DateField(verbose_name="Date Conclusion", blank=True, null=True)
    drinks = models.ManyToManyField(Drink)

    class Meta:
        ordering = ["dateL"]

    def is_current(self):
        if not self.dateC or self.dateC >= date.today():
            return True
        return False

    def __str__(self):
        return self.name


class Rating(models.Model):
    rating = models.IntegerField()
    notes = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)

    class Meta:
        ordering = ["date"]

    def __str__(self):
        return f"[{self.drink.name}] {self.date} - {self.rating}"


# TODO: Voto Compatibilità


# Proxy Class to customize the Django User Model
# https://docs.djangoproject.com/en/dev/topics/auth/customizing/#extending-the-existing-user-model
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

drinc/ratings/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Drink, Rating


class IndexView(generic.ListView):
    template_name = "ratings/index.html"
    context_object_name = "latest_drink_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Drink.objects.order_by("-price")[:5]  # TODO: uso date dei menu per prendere i più recenti


class DetailView(generic.DetailView):
    model = Drink
    template_name = "ratings/detail.html"


class RatingsView(generic.DetailView):
    model = Drink
    template_name = "ratings/results.html"


def vote(request, drink_id):
    drink = get_object_or_404(Drink, pk=drink_id)
    try:
        rating = float(request.POST["rating"])
    except (ValueError):
        # Redisplay the question voting form.
        return render(
            request,
            "ratings/detail.html",
            {
                "drink": drink,
                "error_message": "Could not read reating. Retry",
            },
        )
    if rating < 0 or rating > 10:
        return render(
            request,
            "ratings/detail.html",
            {
                "drink": drink,
                "error_message": "Invalid value found in rating. Rating should be between 0 and 10",
            },
        )
    notes = str(request.POST["notes"]).strip()

    rating = Rating(drink_id=drink.id, rating=rating, notes=notes)
    rating.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse("ratings:ratings", args=(drink.id,)))

drinc/ratings/templates/ratings/detail.html
<h1>{{ drink.name }}</h1>
<ul>
{% for ing in drink.ingredients.all %}
    <li>[{{ ing.category }}] {{ ing.name }}</li>
{% endfor %}
</ul>

<form action="{% url 'ratings:vote' drink.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ drink.name }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <input type="number" name="rating" id="rating" min="0" max="10">
        <label for="rating">Rate this drink</label>
        <input type="text" name="notes" id="notes">
        <label for="notes">Additional Notes</label>
    </fieldset>
    <input type="submit" value="Vote">
</form>

drinc/ratings/templates/ratings/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'ratings/style.css' %}">

{% if latest_drink_list %}
    <ul>
    {% for drink in latest_drink_list %}
        <li><a href="{% url 'ratings:detail' drink.id %}">{{ drink.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No drinks are available.</p>
{% endif %}

drinc/ratings/templates/ratings/results.html
<h1>{{ drink.name }}</h1>

<ul>
{% for rating in drink.rating_set.all %}
    <li>[{{ rating.date }}] {{ rating.rating }} -- {{ rating.notes }}</li>
{% endfor %}
</ul>

<a href="{% url 'ratings:detail' drink.id %}">Vote again?</a>